# Decision Trees

## Decision Trees Regression

In [13]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_boston
from sklearn.datasets import load_iris

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor

In [14]:
X, y = load_boston(return_X_y=True)
print(X.shape)
print(y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
model = DecisionTreeRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

(506, 13)
(506,)


/opt/anaconda3/envs/DA_Env/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housi

0.7149323518245201

In [15]:
scores=cross_val_score(model, X_train, y_train, cv=10)
scores

array([0.82540832, 0.84700245, 0.8886276 , 0.24895324, 0.80434867,
       0.81566503, 0.7433382 , 0.87937923, 0.77393237, 0.57695602])

In [16]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.74 accuracy with a standard deviation of 0.18


## Decision Trees Classification

In [17]:
X, y = load_iris(return_X_y=True)
print(X.shape)
print(y.shape)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
model.score(X_test, y_test)

(150, 4)
(150,)


0.9333333333333333

In [18]:
set(y)

{0, 1, 2}

In [19]:
scores=cross_val_score(model, X_train, y_train, cv=10)
scores

array([0.90909091, 0.90909091, 0.90909091, 1.        , 0.81818182,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [20]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.95 accuracy with a standard deviation of 0.06


In [21]:
y_pred = cross_val_predict(model, X_test, y_test, cv=5)
y_pred

array([1, 2, 0, 1, 0, 2, 0, 2, 0, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 2, 2, 0, 1, 0, 0, 0, 2, 0, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 0,
       0])

### Models Comparision

In [22]:
model1 = DecisionTreeRegressor()

model2 = LinearRegression()

model3 = KNeighborsRegressor()


model_pipeline = [model1, model2, model3]
model_names = ['Regression Tree', 'Linear Regression', 'KNN']
scores = {}
i=0
for model in model_pipeline:
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=10))
    scores[model_names[i]] = mean_score
    i = i+1
print(scores)

{'Regression Tree': 0.9418669080535441, 'Linear Regression': 0.9276531807871432, 'KNN': 0.9694082778314991}
