# Decision Trees

## Decision Trees Regression

In [34]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_boston
from sklearn.datasets import load_iris

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier

In [58]:
X, y = load_boston(return_X_y=True)
print(X.shape)
print(y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
model = DecisionTreeRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

(506, 13)
(506,)


0.7779133458311951

In [43]:
scores=cross_val_score(model, X_train, y_train, cv=10)
scores

array([0.97333333, 0.9912    , 0.88421053, 0.97659574, 1.        ,
       0.9942029 , 0.87142857, 0.9884058 , 0.9942029 , 1.        ])

In [44]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.97 accuracy with a standard deviation of 0.05


## Decision Trees Classification

In [49]:
X, y = load_iris(return_X_y=True)
print(X.shape)
print(y.shape)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
model.score(X_test, y_test)

(150, 4)
(150,)


0.9555555555555556

In [54]:
set(y)

{0, 1, 2}

In [50]:
scores=cross_val_score(model, X_train, y_train, cv=10)
scores

array([0.90909091, 0.90909091, 0.90909091, 1.        , 0.90909091,
       1.        , 0.8       , 0.9       , 0.9       , 1.        ])

In [47]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.94 accuracy with a standard deviation of 0.07


In [48]:
y_pred = cross_val_predict(model, X_test, y_test, cv=5)
y_pred

array([0, 1, 2, 2, 2, 2, 2, 1, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 2, 0, 2,
       2, 0, 2, 0, 2, 2, 2, 1, 1, 1, 2, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       2])

### Models Comparision

In [59]:
model1 = DecisionTreeRegressor()

model2 = LinearRegression()

model3 = KNeighborsRegressor()


model_pipeline = [model1, model2, model3]
model_names = ['Regression Tree', 'Linear Regression', 'KNN']
scores = {}
i=0
for model in model_pipeline:
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=10))
    scores[model_names[i]] = mean_score
    i = i+1
print(scores)

{'Regression Tree': 0.6848157152556744, 'Linear Regression': 0.7034975108097336, 'KNN': 0.47133636735937223}
